extend type AdherenceRecord {
  """
  ✨ Implicit foreign key field based on `AdherenceRecord`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "AdherenceRecord.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `AdherenceRecord`.`medication`. It must match the value of `Medication`.`id`. See `@ref` for how to customize it.
  """
  medicationId: UUID! @fdc_generated(from: "AdherenceRecord.medication", purpose: IMPLICIT_REF_FIELD)
}
extend type Friendship {
  """
  ✨ Implicit foreign key field based on `Friendship`.`requestor`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  requestorId: UUID! @fdc_generated(from: "Friendship.requestor", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Friendship`.`recipient`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  recipientId: UUID! @fdc_generated(from: "Friendship.recipient", purpose: IMPLICIT_REF_FIELD)
}
extend type Medication {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Medication", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Medication`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Medication.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
